# Generated by Django 3.2.9 on 2022-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breastCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_mean', models.FloatField(blank=True, default=None, null=True)),
                ('texture_mean', models.FloatField(blank=True, default=None, null=True)),
                ('perimeter_mean', models.FloatField(blank=True, default=None, null=True)),
                ('area_mean', models.FloatField(blank=True, default=None, null=True)),
                ('smoothness_mean', models.FloatField(blank=True, default=None, null=True)),
                ('compactness_mean', models.FloatField(blank=True, default=None, null=True)),
                ('concavity_mean', models.FloatField(blank=True, default=None, null=True)),
                ('concave_points_mean', models.FloatField(blank=True, default=None, null=True)),
                ('symmetry_mean', models.FloatField(blank=True, default=None, null=True)),
                ('radius_se', models.FloatField(blank=True, default=None, null=True)),
                ('perimeter_se', models.FloatField(blank=True, default=None, null=True)),
                ('compactness_se', models.FloatField(blank=True, default=None, null=True)),
                ('area_se', models.FloatField(blank=True, default=None, null=True)),
                ('concavity_se', models.FloatField(blank=True, default=None, null=True)),
                ('concave_points_se', models.FloatField(blank=True, default=None, null=True)),
                ('fractal_dimension_se', models.FloatField(blank=True, default=None, null=True)),
                ('radius_worst', models.FloatField(blank=True, default=None, null=True)),
                ('texture_worst', models.FloatField(blank=True, default=None, null=True)),
                ('perimeter_worst', models.FloatField(blank=True, default=None, null=True)),
                ('area_worst', models.FloatField(blank=True, default=None, null=True)),
                ('smoothness_worst', models.FloatField(blank=True, default=None, null=True)),
                ('compactness_worst', models.FloatField(blank=True, default=None, null=True)),
                ('concavity_worst', models.FloatField(blank=True, default=None, null=True)),
                ('concave_points_worst', models.FloatField(blank=True, default=None, null=True)),
                ('symmetry_worst', models.FloatField(blank=True, default=None, null=True)),
                ('fractal_dimension_worst', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
