# Generated by Django 3.2.9 on 2022-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.FloatField(blank=True, default=None, null=True)),
                ('glucose', models.FloatField(blank=True, default=None, null=True)),
                ('bloodpressure', models.FloatField(blank=True, default=None, null=True)),
                ('skinthickness', models.FloatField(blank=True, default=None, null=True)),
                ('insulin', models.FloatField(blank=True, default=None, null=True)),
                ('bmi', models.FloatField(blank=True, default=None, null=True)),
                ('dpf', models.FloatField(blank=True, default=None, null=True)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('sex', models.FloatField(blank=True, default=None, null=True)),
                ('cp', models.FloatField(blank=True, default=None, null=True)),
                ('trestbps', models.FloatField(blank=True, default=None, null=True)),
                ('chol', models.FloatField(blank=True, default=None, null=True)),
                ('fbs', models.FloatField(blank=True, default=None, null=True)),
                ('restecg', models.FloatField(blank=True, default=None, null=True)),
                ('thalach', models.FloatField(blank=True, default=None, null=True)),
                ('exang', models.FloatField(blank=True, default=None, null=True)),
                ('oldpeak', models.FloatField(blank=True, default=None, null=True)),
                ('slope', models.FloatField(blank=True, default=None, null=True)),
                ('ca', models.FloatField(blank=True, default=None, null=True)),
                ('thal', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kidney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('bp', models.FloatField(blank=True, default=None, null=True)),
                ('al', models.FloatField(blank=True, default=None, null=True)),
                ('su', models.FloatField(blank=True, default=None, null=True)),
                ('rbc', models.FloatField(blank=True, default=None, null=True)),
                ('pc', models.FloatField(blank=True, default=None, null=True)),
                ('pcc', models.FloatField(blank=True, default=None, null=True)),
                ('ba', models.FloatField(blank=True, default=None, null=True)),
                ('bgr', models.FloatField(blank=True, default=None, null=True)),
                ('bu', models.FloatField(blank=True, default=None, null=True)),
                ('sc', models.FloatField(blank=True, default=None, null=True)),
                ('pot', models.FloatField(blank=True, default=None, null=True)),
                ('wc', models.FloatField(blank=True, default=None, null=True)),
                ('htn', models.FloatField(blank=True, default=None, null=True)),
                ('dm', models.FloatField(blank=True, default=None, null=True)),
                ('cad', models.FloatField(blank=True, default=None, null=True)),
                ('pe', models.FloatField(blank=True, default=None, null=True)),
                ('ane', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='liver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('Total_Bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('Direct_Bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('Alkaline_Phosphotase', models.FloatField(blank=True, default=None, null=True)),
                ('Alamine_Aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('Aspartate_Aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('Total_Protiens', models.FloatField(blank=True, default=None, null=True)),
                ('Albumin', models.FloatField(blank=True, default=None, null=True)),
                ('Albumin_and_Globulin_Ratio', models.FloatField(blank=True, default=None, null=True)),
                ('Gender_Male', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='malaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pneumonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
